services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:80
    environment:
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_NAME=stocktrust
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
