services:
  page:
    build:
      context: ./page
    ports:
      - 8082
    depends_on:
      - postgres
    environment:
      - PAGE_PORT=:8082
      - MSEMK_PORT=:8081
      - MSEMK_DOMAIN=msemk
      - MSEMK_VERSION=v1
    networks:
      - app-network

  msemk:
    build:
      context: ./msemk
    ports:
      - 8081
    depends_on:
      - postgres
    environment:
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_NAME=stocktrust
      - MSEMK_DOMAIN=msemk
      - MSEMK_PORT=:8081
      - MSEMK_VERSION=v1
    networks:
      - app-network

  scraper:
    build:
      context: ./scraper
    ports:
      - 8083
    depends_on:
      - postgres
    environment:
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_NAME=stocktrust
      - SCRAPE_PORT=:8083
      - NUM_THREADS=2
    networks:
      - app-network

  postgres:
    image: postgres
    container_name: stocktrust-db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=stocktrust
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - page
      - scraper
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
