FROM golang:1.23

WORKDIR /usr/src/app
COPY go.mod go.sum ./
RUN go mod download && go mod verify
COPY . .

RUN apt-get update && apt-get install cron -y
COPY startscrape.sh /etc/cron.d/startscrape.sh
RUN chmod 0644 /etc/cron.d/startscrape.sh
RUN crontab /etc/cron.d/startscrape.sh
RUN touch /var/log/cron.log

RUN go build -o app .

CMD cron & ./app
# CMD ["./app"]
